spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: springbootdb
      username: admin
      password: admin123
      authentication-database: admin

server:
  port: 49001