version: '3.8'
services:
  neo4j:
    image: neo4j:3.5.5
    container_name: neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7473:7473"  # HTTPS
      - "7687:7687"  # Bolt
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./import:/import
      - ./plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/casino-young-status-july-nominal-8038
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=1g
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]  # 安装插件（可选）
    restart: always
