version: '3.8'

services:
  mongodb:
    image: mongo:5.0.14  # 与Spring Boot 2.7兼容的MongoDB版本
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "./data/db:/data/db"  # 数据持久化
      - "./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=springbootdb
